-- AquaGold Smart CRM + Geospatial foundation for Neon Postgres
-- Server-only database access from the AquaGold backend/Vercel functions.

create extension if not exists postgis;
create extension if not exists pg_trgm;

create table if not exists public.customers_v2 (
  id uuid primary key default gen_random_uuid(),
  first_name text,
  last_name text not null,
  normalized_name text generated always as (lower(trim(concat_ws(' ', first_name, last_name)))) stored,
  address text,
  location geography(point, 4326),
  location_accuracy_m numeric,
  device_model text,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_phones (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers_v2(id) on delete cascade,
  phone text not null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(customer_id, phone)
);

create table if not exists public.service_visits (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers_v2(id) on delete cascade,
  registered_by text,
  visitor_code text,
  service_type text,
  description text,
  amount bigint not null default 0 check (amount >= 0),
  payment_method text,
  status text not null default 'registered',
  scheduled_from timestamptz,
  scheduled_until timestamptz,
  visited_at timestamptz,
  visit_location geography(point, 4326),
  raw_chat_input text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_items (
  id bigint generated by default as identity primary key,
  service_visit_id uuid not null references public.service_visits(id) on delete cascade,
  item_name text not null,
  quantity numeric not null default 1 check (quantity > 0),
  unit_price bigint check (unit_price is null or unit_price >= 0),
  notes text
);

create table if not exists public.ai_intake_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id text,
  active_customer_id uuid references public.customers_v2(id) on delete set null,
  active_visit_id uuid references public.service_visits(id) on delete set null,
  context jsonb not null default '{}'::jsonb,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists customers_v2_location_gix on public.customers_v2 using gist (location);
create index if not exists customers_v2_name_trgm_idx on public.customers_v2 using gin (normalized_name gin_trgm_ops);
create index if not exists customer_phones_phone_idx on public.customer_phones (phone);
create index if not exists service_visits_customer_created_idx on public.service_visits (customer_id, created_at desc);
create index if not exists service_visits_visit_location_gix on public.service_visits using gist (visit_location);

-- Example nearest-customer query used by the backend:
-- select c.id, c.first_name, c.last_name, c.address,
--        st_distance(c.location, st_setsrid(st_makepoint(:lng, :lat), 4326)::geography) as distance_m
-- from public.customers_v2 c
-- where c.location is not null
--   and st_dwithin(c.location, st_setsrid(st_makepoint(:lng, :lat), 4326)::geography, :radius_m)
-- order by distance_m asc;
