-- AquaGold core application tables for Neon Postgres
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  first_name text,
  last_name text,
  role text not null default 'user',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  quantity integer not null default 0,
  min_quantity integer not null default 0,
  unit text,
  price bigint not null default 0 check (price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inventory_name_idx on public.inventory (name);
create index if not exists users_username_idx on public.users (username);
