-- AquaGold 003: finance, reports, customer identity, editable map metadata

alter table public.customers_v2
  add column if not exists map_label text,
  add column if not exists unit_no text,
  add column if not exists plaque text,
  add column if not exists location_source text,
  add column if not exists archived boolean not null default false;

alter table public.service_visits
  add column if not exists invoice_amount bigint not null default 0,
  add column if not exists received_amount bigint not null default 0,
  add column if not exists company_share_percent numeric(5,2) not null default 50,
  add column if not exists company_share_amount bigint not null default 0,
  add column if not exists customer_balance bigint not null default 0,
  add column if not exists next_service_at timestamptz;

update public.service_visits
set invoice_amount = case when invoice_amount = 0 then amount else invoice_amount end,
    received_amount = case when received_amount = 0 then amount else received_amount end,
    company_share_amount = case when company_share_amount = 0 then round((case when received_amount = 0 then amount else received_amount end) * company_share_percent / 100.0)::bigint else company_share_amount end,
    customer_balance = greatest((case when invoice_amount = 0 then amount else invoice_amount end) - (case when received_amount = 0 then amount else received_amount end), 0)
where amount > 0;

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  category text not null,
  title text not null,
  amount bigint not null check (amount >= 0),
  expense_date timestamptz not null default now(),
  service_visit_id uuid references public.service_visits(id) on delete set null,
  customer_id uuid references public.customers_v2(id) on delete set null,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_settlements (
  id uuid primary key default gen_random_uuid(),
  amount bigint not null check (amount >= 0),
  settled_at timestamptz not null default now(),
  period_from timestamptz,
  period_to timestamptz,
  notes text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings(key,value)
values ('finance', '{"company_share_percent":50}'::jsonb)
on conflict(key) do nothing;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  changed_by text,
  created_at timestamptz not null default now()
);

create index if not exists expenses_date_idx on public.expenses(expense_date desc);
create index if not exists expenses_category_idx on public.expenses(category);
create index if not exists company_settlements_date_idx on public.company_settlements(settled_at desc);
create index if not exists service_visits_visited_idx on public.service_visits(coalesce(visited_at, created_at) desc);
create index if not exists service_visits_next_service_idx on public.service_visits(next_service_at) where next_service_at is not null;
create index if not exists customers_v2_map_label_trgm_idx on public.customers_v2 using gin (map_label gin_trgm_ops);
