-- AquaGold v4 commerce: editable product catalog and professional invoices

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'filter',
  description text,
  price bigint not null default 0 check (price >= 0),
  image_url text,
  badge text,
  origin text,
  lifetime_text text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_no bigint generated by default as identity unique,
  customer_id uuid references public.customers_v2(id) on delete set null,
  issued_at timestamptz not null default now(),
  subtotal bigint not null default 0 check (subtotal >= 0),
  discount bigint not null default 0 check (discount >= 0),
  total bigint not null default 0 check (total >= 0),
  notes text,
  status text not null default 'issued',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  title text not null,
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  unit_price bigint not null default 0 check (unit_price >= 0),
  line_total bigint not null default 0 check (line_total >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists products_active_sort_idx on public.products(is_active, sort_order, created_at desc);
create index if not exists invoices_issued_at_idx on public.invoices(issued_at desc);
create index if not exists invoices_customer_idx on public.invoices(customer_id, issued_at desc);
create index if not exists invoice_items_invoice_idx on public.invoice_items(invoice_id, sort_order);
