/* Finance owns only #aqua-finance. It never replaces the app, navigation or other reports. */
(()=>{'use strict';
const palette=['#30dbb4','#53a6ff','#b28aff','#ffca62','#ff83ae','#45dce9','#94a8c6'];
const labels={cash:'نقد',card:'کارت‌خوان',transfer:'کارت به کارت',cheque:'چک',credit:'اعتباری',other:'سایر',unknown:'نامشخص'};
const catLabels={fuel:'سوخت',parts:'قطعات',food:'غذا',transport:'رفت‌وآمد',other:'سایر',salary:'حقوق',rent:'اجاره',tools:'ابزار',personal:'شخصی'};
const en=v=>String(v??'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const fa=v=>String(v??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const money=v=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:0}).format(Number(v)||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const jp=v=>{const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(v)?v+'T12:00:00+03:30':v),o={};new Intl.DateTimeFormat('en-US-u-ca-persian',{timeZone:'Asia/Tehran',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(d).forEach(p=>{if(['year','month','day'].includes(p.type))o[p.type]=Number(p.value)});return o};
const isoDay=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
const dateFa=v=>{if(!v)return'انتخاب تاریخ';const p=jp(v);return fa(`${p.year}/${String(p.month).padStart(2,'0')}/${String(p.day).padStart(2,'0')}`)};
const dateTimeFa=v=>dateFa(v)+' • '+new Intl.DateTimeFormat('fa-IR',{timeZone:'Asia/Tehran',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v));
const monthNames=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const gregCache=new Map();
function gregorian(year,month,day){const key=`${year}/${month}/${day}`;if(gregCache.has(key))return gregCache.get(key);let d=new Date(Date.UTC(year+621,2,18,12));for(let i=0;i<370;i++){const p=jp(d.toISOString());if(p.year===year&&p.month===month&&p.day===day){const out=d.toISOString().slice(0,10);gregCache.set(key,out);return out}d.setUTCDate(d.getUTCDate()+1)}throw Error('تاریخ شمسی معتبر نیست')}
function groupedDays(days,yearOnly=false){const map=new Map();for(const d of days){const p=jp(d.date),key=yearOnly?String(p.year):`${p.year}/${String(p.month).padStart(2,'0')}`;if(!map.has(key))map.set(key,{label:fa(key),key,received:0,expenses:0,company_share:0,net_profit:0,services:0,settled:0,customer_balance:0});const out=map.get(key);for(const k of ['received','expenses','company_share','net_profit','services','settled','customer_balance'])out[k]+=Number(d[k]||0)}return [...map.values()].sort((a,b)=>a.key.localeCompare(b.key))}
const arrow='<svg class="af-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>';
const chartDefs=[
['payments','دوناتی روش‌های پرداخت','سهم هر روش از دریافتی واقعی'],['area','مساحتی جریان مالی','دریافتی، هزینه و سود در ماه‌های شمسی'],
['gauge','عقربه‌ای تسویه شرکت','درصد تسویه سهم شرکت در همین بازه'],['goal','عقربه‌ای هدف درآمد','پیشرفت نسبت به هدف انتخابی شما'],
['radar','عنکبوتی مقایسه ماه‌ها','دو ماه آخر بازه؛ هر محور نسبت به بیشینه همان شاخص'],['scatter','پراکندگی دریافتی سرویس‌ها','هر نقطه یک سرویس؛ محور افقی تاریخ شمسی'],
['wave','منحنی نرم درآمد و هزینه','منحنی روی داده واقعی؛ نقاط، مقدار ثبت‌شده هستند'],['services','میله‌ای انواع سرویس','دریافتی به تفکیک نوع خدمت'],
['customers','میله‌ای مشتری‌های برتر','ده مشتری با بیشترین دریافتی در بازه'],['expenses','دوناتی دسته‌های هزینه','سهم هر دسته از هزینه‌های بازه'],
['yearly','میله‌ای مقایسه سال‌ها','جمع سال شمسی در محدوده انتخابی'],['settled','مساحتی تسویه و سهم شرکت','مقایسه ماهانه سهم ایجادشده و پرداخت شرکت'],
['debt','میله‌ای مانده مشتری‌ها','ده مشتری با بیشترین مانده در بازه'],['visits','میله‌ای تعداد سرویس','تعداد سرویس‌های واقعی در ماه‌های شمسی']];
function accordion(id,title,sub,body){return `<article class="af-card" data-fold="${id}"><button type="button" class="af-toggle" data-toggle="${id}" aria-expanded="false" aria-controls="af-panel-${id}"><span><h3>${esc(title)}</h3><small>${esc(sub)}</small></span>${arrow}</button><div class="af-fold" id="af-panel-${id}" inert><div><div class="af-fold-pad">${body}</div></div></div></article>`}
const api=async(path,opts={})=>{const headers={'Content-Type':'application/json',...opts.headers};if(opts.method&&opts.method!=='GET'){const c=document.cookie.split('; ').find(x=>x.startsWith('aquagold_csrf='));if(c)headers['X-CSRF-Token']=decodeURIComponent(c.split('=').slice(1).join('='));headers['Idempotency-Key']=opts.key||crypto.randomUUID()}const r=await fetch('/api'+path,{...opts,headers,credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'ارتباط با سرور برقرار نشد');return d};
function boot(){const root=document.getElementById('aqua-finance');if(!root)return;
let report=null,busy=false,loading=false,active=false,loadGeneration=0,editId=null,paymentPage=1,settlementPage=1,calendar=null;
const chartMap=new Map(),openFolds=new Set(),dates={from:'',to:'',settlement:isoDay(new Date())};let goal=0;
try{goal=Number(localStorage.getItem('aq_finance_goal'))||0}catch{}
root.innerHTML=`<div class="af-top"><div><div class="af-eyebrow">AQUAGOLD / FINANCE</div><h2>نبض مالی آکوا</h2><p><span class="af-live"></span>گزارش یکپارچه دریافتی، سود و تسویه</p></div><div class="af-toolbar"><select id="af-print-mode" class="af-btn" aria-label="نوع گزارش چاپی"><option value="summary">چاپ خلاصه</option><option value="full">گزارش کامل با نمودارها</option></select><button class="af-btn" data-action="print">PDF / چاپ</button></div></div>
<div class="af-card af-pad"><div class="af-toolbar" style="justify-content:space-between"><h3>بازه گزارش • تقویم شمسی</h3><div class="af-toolbar"><button class="af-btn" data-action="all">همه سوابق</button><button class="af-btn" data-action="month">این ماه</button></div></div><div class="af-grid" style="margin-top:12px">${dateControl('from','از تاریخ')}${dateControl('to','تا تاریخ')}</div><div class="af-toolbar" style="margin-top:14px"><button class="af-btn af-primary" data-action="load">اعمال بازه / تازه‌سازی</button><span id="af-range" style="font-size:11px;color:#a6bdd4">همه سوابق</span></div><p>تمام کارت‌ها و نمودارها از همین بازه محاسبه می‌شوند؛ سرویس‌های لغوشده و برنامه‌ریزی‌شده در جمع مالی نیستند.</p></div>
<div id="af-status" class="af-status" role="status" aria-live="polite"></div><div id="af-stats" class="af-stats"></div><div id="af-payment-note"></div>
<div class="af-charts">${chartDefs.map(([id,title,sub])=>accordion(id,title,sub,(id==='goal'?'<label>هدف درآمد بازه (تومان)<input class="af-field" id="af-goal" inputmode="numeric" placeholder="مثلاً ۲۰۰٬۰۰۰٬۰۰۰" aria-label="هدف درآمد بازه"></label><button class="af-btn" data-action="goal" style="margin:10px 0">ثبت هدف</button>':'')+`<div id="af-value-${id}" class="af-gauge-value"></div><div class="af-chart"><canvas id="af-chart-${id}" role="img" aria-label="${title}"></canvas></div><p id="af-note-${id}"></p>`)).join('')}</div>
<div id="af-admin" hidden><div class="af-card af-pad"><h3 id="af-form-title">ثبت تسویه با شرکت</h3><form id="af-settlement-form" class="af-form" style="margin-top:16px" autocomplete="off"><label>مبلغ پرداخت‌شده (تومان)<input id="af-amount" class="af-field" inputmode="numeric" autocomplete="transaction-amount" required placeholder="مبلغ به تومان"></label><div class="af-grid">${dateControl('settlement','تاریخ شمسی تسویه')}<label>ساعت تهران<input id="af-time" class="af-field" type="time" required value="12:00"></label></div><label>توضیحات<textarea id="af-notes" class="af-field" maxlength="4000" rows="2" placeholder="توضیح تسویه"></textarea></label><div class="af-toolbar"><button id="af-save" type="submit" class="af-btn af-primary">ثبت تسویه</button><button type="button" class="af-btn" data-action="cancel-edit" hidden id="af-cancel-edit">انصراف از ویرایش</button></div><span id="af-form-status" class="af-status" role="status"></span></form></div>
${accordion('history','سابقه تسویه با شرکت','تاریخ شمسی، مبلغ، توضیحات و ویرایش / حذف','<div id="af-history"></div>')}
${accordion('payment-edit','بررسی و اصلاح روش پرداخت','تعیین روش پرداخت بدون تغییر مبلغ سرویس','<div class="af-toolbar"><select id="af-payment-filter" class="af-field" style="max-width:200px;margin:0"><option value="all">همه روش‌ها</option>'+Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')+'</select></div><div id="af-payment-records"></div>')}
</div>`;
function dateControl(key,label){return `<label class="af-datewrap">${label}<button type="button" class="af-field af-datebtn" data-date="${key}" aria-expanded="false"><span id="af-date-${key}">${dateFa(dates[key])}</span><span aria-hidden="true">▦</span></button></label>`}
function status(message,error=false,form=false){const el=root.querySelector(form?'#af-form-status':'#af-status');el.textContent=message;el.classList.toggle('af-error',error)}
function updateDate(key){root.querySelector('#af-date-'+key).textContent=dateFa(dates[key])}
function closeCalendar(){root.querySelector('.af-calendar')?.remove();root.querySelectorAll('[data-date]').forEach(b=>b.setAttribute('aria-expanded','false'));calendar=null}
function renderCalendar(){root.querySelector('.af-calendar')?.remove();if(!calendar)return;const {key,year,month}=calendar,first=gregorian(year,month,1),firstDay=(new Date(first+'T12:00:00Z').getUTCDay()+1)%7;let count=month<=6?31:30;if(month===12){try{gregorian(year,12,30)}catch{count=29}}
const panel=document.createElement('div');panel.className='af-calendar';panel.setAttribute('role','group');panel.setAttribute('aria-label','انتخاب تاریخ شمسی');panel.innerHTML=`<div class="af-toolbar" style="justify-content:space-between"><button class="af-btn" type="button" data-cal="prev" aria-label="ماه قبل">‹</button><b>${monthNames[month-1]} ${fa(year)}</b><button class="af-btn" type="button" data-cal="next" aria-label="ماه بعد">›</button></div><div class="af-calendar-grid">${['ش','ی','د','س','چ','پ','ج'].map(x=>`<small>${x}</small>`).join('')}${'<span></span>'.repeat(firstDay)}${Array.from({length:count},(_,i)=>{const d=gregorian(year,month,i+1);return `<button type="button" data-day="${d}" class="${dates[key]===d?'af-selected':''}">${fa(i+1)}</button>`}).join('')}</div><div class="af-toolbar" style="margin-top:10px"><button class="af-btn" type="button" data-cal="today">امروز</button><button class="af-btn" type="button" data-cal="close">بستن</button></div>`;root.querySelector(`[data-date="${key}"]`).parentElement.appendChild(panel);const rect=panel.getBoundingClientRect();if(rect.left<8){panel.style.right='auto';panel.style.left='0'} }
function destroyCharts(){for(const chart of chartMap.values())chart.destroy();chartMap.clear()}
function setFold(id,open){const card=root.querySelector(`[data-fold="${id}"]`);if(!card)return;card.classList.toggle('af-open',open);card.querySelector('.af-toggle').setAttribute('aria-expanded',String(open));card.querySelector('.af-fold').inert=!open;if(open){openFolds.add(id);if(chartDefs.some(x=>x[0]===id))requestAnimationFrame(()=>drawChart(id))}else{openFolds.delete(id);chartMap.get(id)?.destroy();chartMap.delete(id)} }
function renderStats(){const t=report.totals,a=report.company_all_time;const stats=[['فروش / فاکتور',t.invoice,palette[1]],['دریافتی',t.received,palette[0]],['سهم شرکت',t.company_share,palette[5]],['هزینه‌ها',t.expenses,palette[3]],['سود خالص',t.net_profit,t.net_profit<0?palette[4]:palette[0]],['تسویه در بازه',t.settled,palette[2]],['مانده شرکت در بازه',t.company_net,palette[3]],['مانده مشتری‌ها',t.customer_balance,palette[4]],...report.payments.filter(p=>['cash','card','transfer','unknown'].includes(p.key)||p.amount!==0).map(p=>[labels[p.key],p.amount,palette[Object.keys(labels).indexOf(p.key)]])];root.querySelector('#af-stats').innerHTML=stats.map(([label,value,tone])=>`<div class="af-card af-stat" style="--tone:${tone}"><small>${label}</small><b>${money(value)}</b><em>تومان</em></div>`).join('');
const unknown=report.payments.find(x=>x.key==='unknown');root.querySelector('#af-payment-note').innerHTML=`${unknown.amount?`<div class="af-note">روش پرداخت ${money(unknown.amount)} تومان مشخص نیست. ${report.can_edit?'از «بررسی و اصلاح روش پرداخت» روش درست را ثبت کنید.':''} هیچ مبلغی به‌صورت حدسی بین روش‌ها تقسیم نشده است.</div>`:''}<div class="af-card af-pad"><div class="af-toolbar" style="justify-content:space-between"><span>${money(t.services)} سرویس • ${money(t.customers)} مشتری در بازه</span><b style="color:${a.balance>=0?palette[3]:palette[0]}">${a.balance>=0?'مانده کل شرکت':'بستانکاری کل از شرکت'}: ${money(Math.abs(a.balance))} تومان</b></div><p>مانده کل شرکت، همه سوابق را پوشش می‌دهد؛ مانده بازه، اختلاف سهم و تسویه داخل بازه است. مقدار منفی یعنی پرداخت بیشتر از سهم.</p></div>`;
root.querySelector('#af-admin').hidden=!report.can_edit;root.querySelector('#af-goal').value=goal?money(goal):'';
const label=report.range.from||report.range.to?`${report.range.from?dateFa(report.range.from):'از ابتدا'} تا ${report.range.to?dateFa(report.range.to):'امروز'}`:'همه سوابق';root.querySelector('#af-range').textContent=label;
root.querySelector('[data-toggle="history"] small').textContent=`${money(report.settlements.length)} تسویه • جمع ${money(t.settled)} تومان`;
renderHistory();renderPayments();}
async function load(){if(loading)return;loading=true;const generation=++loadGeneration;status('در حال دریافت اطلاعات مالی…');root.querySelector('[data-action="load"]').disabled=true;try{const query=new URLSearchParams();if(dates.from)query.set('from',dates.from);if(dates.to)query.set('to',dates.to);const next=await api('/finance/dashboard?'+query);if(generation!==loadGeneration)return;report=next;paymentPage=1;settlementPage=1;destroyCharts();renderStats();for(const id of openFolds)if(chartDefs.some(x=>x[0]===id))drawChart(id);status('گزارش به‌روز شد • همه مبالغ به تومان')}catch(e){status(e.message,true)}finally{loading=false;root.querySelector('[data-action="load"]').disabled=false}}
function pagination(page,total,type){const pages=Math.max(1,Math.ceil(total/20));return `<div class="af-pagination"><button type="button" class="af-btn" data-page="${type}" data-step="-1" ${page===1?'disabled':''}>قبلی</button><span>${fa(page)} / ${fa(pages)}</span><button type="button" class="af-btn" data-page="${type}" data-step="1" ${page>=pages?'disabled':''}>بعدی</button></div>`}
function renderHistory(){const rows=report.settlements;root.querySelector('#af-history').innerHTML=rows.length?rows.slice((settlementPage-1)*20,settlementPage*20).map(s=>`<div class="af-row"><div><b>${money(s.amount)} تومان</b><small>${dateTimeFa(s.settled_at)}</small><small>${esc(s.notes||'بدون توضیح')}</small></div><div class="af-toolbar"><button class="af-btn" data-edit="${s.id}">ویرایش</button><button class="af-btn af-danger" data-delete="${s.id}">حذف</button></div></div>`).join('')+pagination(settlementPage,rows.length,'history'):'<div class="af-empty">تسویه‌ای در این بازه ثبت نشده است.</div>'}
function renderPayments(){const filter=root.querySelector('#af-payment-filter').value,rows=report.records.filter(r=>filter==='all'||r.method===filter);root.querySelector('#af-payment-records').innerHTML=rows.length?rows.slice((paymentPage-1)*20,paymentPage*20).map(r=>`<div class="af-row"><div><b>${esc(r.name)} • ${money(r.amount)} تومان</b><small>${dateFa(r.date)} • ${esc(r.service_type)}</small><small>روش ثبت‌شده: ${esc(r.raw_method||'خالی')}</small></div><div class="af-toolbar"><select class="af-field" data-method="${r.id}" aria-label="روش پرداخت ${esc(r.name)}"><option value="unknown" ${r.method==='unknown'?'selected':''} disabled>نامشخص</option>${Object.entries(labels).filter(([k])=>k!=='unknown').map(([k,v])=>`<option value="${k}" ${r.method===k?'selected':''}>${v}</option>`).join('')}</select><button class="af-btn" data-payment-save="${r.id}">ذخیره</button></div></div>`).join('')+pagination(paymentPage,rows.length,'payments'):'<div class="af-empty">رکوردی برای این روش پرداخت وجود ندارد.</div>'}
function chartConfig(id,print=false){const d=report,t=d.totals,months=groupedDays(d.days),years=groupedDays(d.days,true),ink=print?'#334155':'#a6bdd4';let type='bar',data={labels:[],datasets:[]},note='',gaugeValue='',extra={},plugins=[];
const series=(label,rows,key,color,fill=false)=>({label,data:rows.map(r=>r[key]),borderColor:color,backgroundColor:fill?color+'28':color,borderWidth:2.5,fill,pointRadius:3,pointHoverRadius:6,tension:0});
const bars=(rows,key='received')=>({labels:rows.map(r=>r.label),datasets:[{label:'تومان',data:rows.map(r=>r[key]),backgroundColor:rows.map((_,i)=>palette[i%palette.length]),borderRadius:7}]});
if(id==='payments'||id==='expenses'){type='doughnut';const rows=id==='payments'?d.payments.filter(x=>x.amount>0):d.expense_categories.filter(x=>x.amount>0);data={labels:rows.map(r=>catLabels[r.label]||r.label),datasets:[{data:rows.map(r=>r.amount),backgroundColor:rows.map((r,i)=>id==='payments'?palette[Object.keys(labels).indexOf(r.key)]:palette[i%7]),borderWidth:2,borderColor:print?'white':'#10263d',hoverOffset:9}]};extra.cutout='68%';gaugeValue=money(id==='payments'?t.received:t.expenses)+' تومان';}
if(id==='area'||id==='wave'){type='line';data={labels:months.map(m=>m.label),datasets:[series('دریافتی',months,'received',palette[0],id==='area'),series('هزینه',months,'expenses',palette[3],id==='area'),series('سود خالص',months,'net_profit',palette[2],id==='area')]};if(id==='wave')data.datasets.forEach(s=>{s.tension=.35;s.cubicInterpolationMode='monotone'});note='محور افقی: ماه شمسی • محور عمودی: تومان';}
if(id==='gauge'||id==='goal'){type='doughnut';const target=id==='gauge'?t.company_share:goal,value=id==='gauge'?t.settled:t.received;const pct=target>0?value/target*100:null;data={labels:['انجام‌شده','باقی‌مانده'],datasets:[{data:pct===null?[]:[Math.min(100,Math.max(0,pct)),Math.max(0,100-pct)],backgroundColor:[id==='gauge'?palette[0]:palette[2],print?'#e2e8f0':'#203b57'],borderWidth:0}]};extra={rotation:-90,circumference:180,cutout:'80%'};gaugeValue=pct===null?'—':money(pct)+'٪';note=target>0?`${money(value)} از ${money(target)} تومان${pct>100?' • بیشتر از '+(id==='goal'?'هدف':'سهم بازه'):''}`:id==='goal'?'برای نمایش عقربه، هدف درآمد این بازه را وارد کنید.':'در این بازه سهمی برای شرکت ثبت نشده است.';plugins=[{id:'financeNeedle',afterDraw(chart){if(pct===null)return;const arc=chart.getDatasetMeta(0).data[0];if(!arc)return;const angle=Math.PI+Math.min(100,Math.max(0,pct))/100*Math.PI,ctx=chart.ctx,r=arc.outerRadius*.8;ctx.save();ctx.translate(arc.x,arc.y);ctx.rotate(angle);ctx.beginPath();ctx.moveTo(-8,-3);ctx.lineTo(r,0);ctx.lineTo(-8,3);ctx.closePath();ctx.fillStyle=print?'#334155':'#f1f5f9';ctx.fill();ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();ctx.restore()}}];}
if(id==='radar'){type='radar';const keys=['received','net_profit','services','settled','expenses'],rows=months.slice(-2);data={labels:['دریافتی','سود مثبت','تعداد سرویس','تسویه','هزینه'],datasets:rows.map((r,i)=>({label:r.label,data:keys.map(k=>{const max=Math.max(...rows.map(x=>Math.max(0,x[k]))),v=Math.max(0,r[k]);return max?v/max*100:0}),borderColor:palette[i===0?1:2],backgroundColor:palette[i===0?1:2]+'30',pointBackgroundColor:palette[i===0?1:2],borderWidth:2}))};note='هر محور مستقل بین ۰ تا ۱۰۰ نرمال شده؛ هزینه بیشتر لزوماً بهتر نیست. زیان روی محور سود مثبت صفر است و مقدار واقعی در کارت سود دیده می‌شود.';extra.scales={r:{min:0,max:100,grid:{color:print?'#cbd5e1':'#34516e'},angleLines:{color:print?'#cbd5e1':'#34516e'},pointLabels:{color:ink,font:{family:'Vazirmatn',size:11}},ticks:{display:false}}};}
if(id==='scatter'){type='scatter';const sorted=[...d.records].sort((a,b)=>a.date.localeCompare(b.date)),rows=sorted.length>1000?sorted.filter((_,i)=>i%Math.ceil(sorted.length/1000)===0):sorted;data={datasets:Object.entries(labels).map(([key,label],i)=>({label,data:rows.filter(r=>r.method===key).map(r=>({x:new Date(r.date+'T12:00:00Z').getTime(),y:r.amount,name:r.name,day:r.date})),backgroundColor:palette[i],pointRadius:5})).filter(x=>x.data.length)};note=`${money(rows.length)} نقطه${sorted.length>1000?'؛ نمونه‌گیری از '+money(sorted.length)+' سرویس؛ جمع‌ها شامل تمام سوابق هستند.':'؛ هر نقطه یک سرویس است.'}`;extra.scales={x:{type:'linear',ticks:{color:ink,maxTicksLimit:4,callback:v=>dateFa(new Date(v).toISOString())},grid:{color:print?'#e2e8f0':'#29425a'}},y:{ticks:{color:ink,callback:money},grid:{color:print?'#e2e8f0':'#29425a'}}};}
if(id==='services')data=bars(d.service_types);
if(id==='customers'){data=bars(d.customers.slice(0,10));extra.indexAxis='y';}
if(id==='debt'){data=bars([...d.customers].filter(r=>r.balance>0).sort((a,b)=>b.balance-a.balance).slice(0,10),'balance');extra.indexAxis='y';}
if(id==='yearly')data={labels:years.map(r=>r.label),datasets:[series('دریافتی',years,'received',palette[1]),series('سود خالص',years,'net_profit',palette[0]),series('هزینه',years,'expenses',palette[3])]};
if(id==='settled'){type='line';data={labels:months.map(r=>r.label),datasets:[series('سهم شرکت',months,'company_share',palette[1],true),series('تسویه شرکت',months,'settled',palette[2],true)]};}
if(id==='visits'){data=bars(months,'services');data.datasets[0].label='تعداد سرویس';}
const hasData=data.datasets.some(s=>s.data.length);if(!hasData&&!note)note='داده‌ای در این بازه وجود ندارد.';
const cartesian=!['doughnut','radar'].includes(type);const scales=cartesian?{x:{ticks:{color:ink,font:{family:'Vazirmatn'},maxRotation:35},grid:{display:false}},y:{beginAtZero:true,ticks:{color:ink,font:{family:'Vazirmatn'},callback:money},grid:{color:print?'#e2e8f0':'#29425a'}}}:undefined;
return {note,gaugeValue,hasData,config:{type,data,plugins,options:{responsive:true,maintainAspectRatio:false,animation:print||matchMedia('(prefers-reduced-motion: reduce)').matches?false:{duration:650},... (scales?{scales}:{}),plugins:{legend:{display:!['gauge','goal','customers','services','debt','visits'].includes(id),position:'bottom',rtl:true,labels:{color:ink,usePointStyle:true,boxWidth:8,padding:16,font:{family:'Vazirmatn',size:10}}},tooltip:{rtl:true,titleFont:{family:'Vazirmatn'},bodyFont:{family:'Vazirmatn'},callbacks:{label:ctx=>id==='scatter'?`${ctx.raw.name}: ${money(ctx.raw.y)} تومان`:['radar','gauge','goal'].includes(id)?`${ctx.dataset.label||ctx.label||''}: ${money(typeof ctx.parsed==='number'?ctx.parsed:ctx.parsed.r)}٪`:`${ctx.dataset.label||ctx.label||''}: ${money(typeof ctx.parsed==='number'?ctx.parsed:(extra.indexAxis==='y'?ctx.parsed.x:ctx.parsed.y))}${id==='visits'?' سرویس':' تومان'}`,title:items=>id==='scatter'?dateFa(items[0].raw.day):items[0]?.label||''}}},...extra}}};}
function drawChart(id){if(!report||!active||!openFolds.has(id))return;const canvas=root.querySelector('#af-chart-'+id);if(!canvas)return;chartMap.get(id)?.destroy();if(typeof Chart==='undefined'){root.querySelector('#af-note-'+id).textContent='نمودار بارگذاری نشد؛ صفحه را تازه کنید.';return}const c=chartConfig(id);root.querySelector('#af-note-'+id).textContent=c.note;root.querySelector('#af-value-'+id).textContent=c.gaugeValue;chartMap.set(id,new Chart(canvas,c.config));}
function resetForm(){editId=null;root.querySelector('#af-settlement-form').reset();dates.settlement=isoDay(new Date());updateDate('settlement');root.querySelector('#af-time').value=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tehran',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());root.querySelector('#af-form-title').textContent='ثبت تسویه با شرکت';root.querySelector('#af-save').textContent='ثبت تسویه';root.querySelector('#af-cancel-edit').hidden=true;status('',false,true)}
function setBusy(value){busy=value;root.querySelectorAll('#af-admin button').forEach(b=>b.disabled=value)}
async function mutate(path,method,payload,success){if(busy)return false;setBusy(true);try{await api(path,{method,body:JSON.stringify(payload)});await load();status(success);return true}catch(e){status(e.message,true);status(e.message,true,true);return false}finally{setBusy(false)}}
root.querySelector('#af-settlement-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const raw=en(root.querySelector('#af-amount').value).replace(/[٬,\s]/g,'');if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw))||Number(raw)<=0){status('مبلغ مثبت و معتبر به تومان وارد کنید',true,true);return}const settled=dates.settlement,time=root.querySelector('#af-time').value;if(!settled||!/^\d{2}:\d{2}$/.test(time)){status('تاریخ و ساعت معتبر وارد کنید',true,true);return}const record=report.settlements.find(s=>s.id===editId),payload={amount:Number(raw),settled_at:`${settled}T${time}:00+03:30`,notes:root.querySelector('#af-notes').value};if(editId&&!record){status('رکورد در بازه فعلی نیست؛ ویرایش را لغو و دوباره انتخاب کنید',true,true);return}if(record)payload.revision=record.revision;const ok=await mutate(editId?'/settlements/'+editId:'/settlements',editId?'PATCH':'POST',payload,editId?'تسویه و مانده شرکت به‌روز شد':'تسویه ثبت شد');if(ok){resetForm();status('ذخیره شد',false,true)}});
root.querySelector('#af-payment-filter').addEventListener('change',()=>{paymentPage=1;renderPayments()});
root.addEventListener('keydown',e=>{if(e.key==='Escape')closeCalendar()});
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
if(b.dataset.toggle){setFold(b.dataset.toggle,!openFolds.has(b.dataset.toggle));return}
if(b.dataset.date){const key=b.dataset.date;if(calendar?.key===key){closeCalendar();return}closeCalendar();const p=jp(dates[key]||isoDay(new Date()));calendar={key,year:p.year,month:p.month};b.setAttribute('aria-expanded','true');renderCalendar();return}
if(b.dataset.cal){const action=b.dataset.cal;if(action==='close'){closeCalendar();return}if(action==='today'){dates[calendar.key]=isoDay(new Date());updateDate(calendar.key);closeCalendar();return}calendar.month+=action==='next'?1:-1;if(calendar.month===13){calendar.month=1;calendar.year++}if(calendar.month===0){calendar.month=12;calendar.year--}renderCalendar();return}
if(b.dataset.day){dates[calendar.key]=b.dataset.day;updateDate(calendar.key);closeCalendar();return}
if(b.dataset.page){if(b.dataset.page==='history'){settlementPage+=Number(b.dataset.step);renderHistory()}else{paymentPage+=Number(b.dataset.step);renderPayments()}return}
if(b.dataset.edit){const s=report.settlements.find(x=>x.id===b.dataset.edit);editId=s.id;root.querySelector('#af-amount').value=money(s.amount);dates.settlement=isoDay(s.settled_at);updateDate('settlement');root.querySelector('#af-time').value=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tehran',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s.settled_at));root.querySelector('#af-notes').value=s.notes||'';root.querySelector('#af-form-title').textContent='ویرایش تسویه با شرکت';root.querySelector('#af-save').textContent='ذخیره تغییرات';root.querySelector('#af-cancel-edit').hidden=false;root.querySelector('#af-form-title').scrollIntoView({behavior:'smooth',block:'center'});return}
if(b.dataset.delete){const s=report.settlements.find(x=>x.id===b.dataset.delete);if(confirm(`تسویه ${money(s.amount)} تومان در ${dateFa(s.settled_at)} حذف شود؟ مانده شرکت دوباره محاسبه می‌شود.`)){const ok=await mutate('/settlements/'+s.id,'DELETE',{revision:s.revision},'تسویه حذف و مانده شرکت به‌روز شد');if(ok&&editId===s.id)resetForm()}return}
if(b.dataset.paymentSave){const r=report.records.find(x=>x.id===b.dataset.paymentSave),method=root.querySelector(`[data-method="${r.id}"]`).value;if(method==='unknown'){status('روش پرداخت را انتخاب کنید',true);return}await mutate('/finance/payments/'+r.id,'PATCH',{payment_method:method,revision:r.revision},'روش پرداخت و نمودارها اصلاح شد');return}
const action=b.dataset.action;if(action==='load')await load();if(action==='all'){dates.from='';dates.to='';updateDate('from');updateDate('to');await load()}if(action==='month'){const p=jp(new Date().toISOString());dates.from=gregorian(p.year,p.month,1);dates.to=isoDay(new Date());updateDate('from');updateDate('to');await load()}if(action==='cancel-edit')resetForm();if(action==='goal'){const raw=en(root.querySelector('#af-goal').value).replace(/[٬,\s]/g,'');if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw))||Number(raw)<=0){status('هدف باید مبلغ مثبت به تومان باشد',true);return}goal=Number(raw);try{localStorage.setItem('aq_finance_goal',String(goal))}catch{}drawChart('goal');status('هدف درآمد روی این دستگاه ذخیره شد')}if(action==='print')printReport();});
function printReport(){if(!report){status('ابتدا گزارش را دریافت کنید',true);return}const full=root.querySelector('#af-print-mode').value==='full',w=window.open('','_blank');if(!w){status('اجازه بازکردن پنجره گزارش را در مرورگر فعال کنید',true);return}const t=report.totals;let charts='';if(full&&typeof Chart!=='undefined'){for(const [id,title] of chartDefs){const info=chartConfig(id,true);if(!info.hasData)continue;const canvas=document.createElement('canvas');canvas.width=920;canvas.height=430;canvas.style.position='fixed';canvas.style.left='-12000px';document.body.appendChild(canvas);info.config.options.responsive=false;info.config.options.animation=false;const chart=new Chart(canvas,info.config);chart.update('none');const img=canvas.toDataURL('image/png');chart.destroy();canvas.remove();charts+=`<figure><h3>${title}</h3><img src="${img}" alt="${title}"><figcaption>${esc(info.gaugeValue)} ${esc(info.note)}</figcaption></figure>`}}
const rows=[['فروش / فاکتور',t.invoice],['دریافتی',t.received],['سهم شرکت',t.company_share],['هزینه‌ها',t.expenses],['سود خالص',t.net_profit],['تسویه در بازه',t.settled],['مانده شرکت در بازه',t.company_net],['مانده مشتری‌ها',t.customer_balance],...report.payments.map(p=>[p.label,p.amount])];
const table=(headers,rows)=>`<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
w.document.open();w.document.write(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>گزارش مالی آکوا</title><link rel="stylesheet" href="${location.origin}/vendor/vazirmatn.css"><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Vazirmatn,sans-serif;background:white;color:#172033;margin:20px;font-size:11px;line-height:1.8}h1{font-size:21px;margin:0}h2{font-size:15px;margin-top:18px}h3{font-size:13px}p{margin:4px 0;color:#475569}table{width:100%;border-collapse:collapse;margin:10px 0}th,td{border-bottom:1px solid #cbd5e1;text-align:right;padding:5px 8px;background:white;color:#172033}th{border-top:1px solid #64748b;font-weight:bold}thead{display:table-header-group}tr,figure{break-inside:avoid;page-break-inside:avoid}figure{margin:12px 0;border:1px solid #ddd;padding:8px}figure img{display:block;width:100%;max-height:92mm;object-fit:contain}figcaption{font-size:9px;color:#475569}.print-btn{padding:12px 22px;background:white;color:#172033;border:1px solid #64748b;border-radius:8px;font:inherit}.summary{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media print{body{margin:0}.no-print{display:none}a{color:inherit}}</style></head><body><button class="print-btn no-print" onclick="window.print()">چاپ / ذخیره PDF</button><h1>گزارش مالی AquaGold</h1><p>${esc(root.querySelector('#af-range').textContent)} • مبالغ به تومان</p><p>تاریخ تهیه: ${dateTimeFa(new Date().toISOString())} • ${money(t.services)} سرویس • ${money(t.customers)} مشتری</p><div class="summary">${table(['عنوان','تومان'],rows.slice(0,8).map(([k,v])=>[k,money(v)]))}${table(['روش پرداخت','تومان'],rows.slice(8).map(([k,v])=>[k,money(v)]))}</div><p>مانده کل شرکت (همه سوابق): ${money(report.company_all_time.balance)} تومان. منفی یعنی بستانکاری.</p>${full?`<h2>سوابق تسویه در بازه</h2>${table(['تاریخ شمسی','مبلغ','توضیح'],report.settlements.map(s=>[dateTimeFa(s.settled_at),money(s.amount),s.notes||'—']))}<h2>دریافتی سرویس‌ها</h2>${table(['تاریخ','مشتری','خدمت','روش پرداخت','تومان'],report.records.map(r=>[dateFa(r.date),r.name,r.service_type,labels[r.method],money(r.amount)]))}<h2>نمودارهای مالی</h2>${charts}`:''}</body></html>`);w.document.close();}
const visibility=()=>{const visible=root.getClientRects().length>0&&!document.hidden;root.classList.toggle('af-paused',!visible);if(visible&&!active){active=true;if(!report)load();else{for(const id of openFolds)drawChart(id);load()}}else if(!visible&&active){active=false;destroyCharts();closeCalendar()}};
const visibleObserver=new MutationObserver(visibility);let ancestor=root;while(ancestor){visibleObserver.observe(ancestor,{attributes:true,attributeFilter:['style']});ancestor=ancestor.parentElement;}document.addEventListener('visibilitychange',visibility);document.addEventListener('click',e=>{if(calendar&&!e.target.closest('#aqua-finance .af-datewrap'))closeCalendar()});resetForm();visibility();
}
window.AquaFinanceMath={jp,gregorian,groupedDays,dateFa,isoDay};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
