"""Bale inbox safety guard.

Prevents AquaGold/Bale bot outbound messages from looping back into the work
inbox, removes already-created self-report ghosts, and lets operators discard
unwanted inbox jobs before they reach the core CRM/service ledger.
"""
from __future__ import annotations

import re

from flask import Response, jsonify, request

import app_v3
import bale_bridge


AQUAGOLD_OUTBOUND_PREFIXES = (
    "❌ لغو کار AquaGold",
    "📊 گزارش پایان کار",
    "📊 گزارش هفتگی",
    "📊 گزارش ماهانه",
    "✅ کار در AquaGold ثبت شد",
    "✅ کار انجام شد و در AquaGold ثبت شد",
    "✅ کار از طریق ثبت هوشمند AquaGold",
    "❌ کار کنسل شد. علت:",
)


def _flat(value):
    return re.sub(r"\s+", " ", str(value or "").replace("\u200c", " ")).strip()


def is_aquagold_outbound(text, sender=None):
    """Return True for messages created by the bot/AquaGold itself."""
    sender = sender or {}
    if sender.get("is_bot") is True:
        return True
    value = _flat(text)
    if not value:
        return False
    if value.startswith(AQUAGOLD_OUTBOUND_PREFIXES):
        return True
    # Management report headings are intentionally recognizable even if Bale
    # omits the sender's is_bot flag in a group/channel update.
    if value.startswith("📊") and "AquaGold" in value[:100]:
        return True
    return False


def _cleanup_self_generated_jobs():
    """Delete only unprocessed ghost jobs generated by AquaGold itself."""
    with app_v3.get_db() as db, db.cursor() as cur:
        cur.execute(
            """delete from bale_jobs
               where status in ('new','review')
                 and service_visit_id is null
                 and (
                   raw_text like '❌ لغو کار AquaGold%%'
                   or raw_text like '📊 گزارش پایان کار%%AquaGold%%'
                   or raw_text like '📊 گزارش هفتگی%%AquaGold%%'
                   or raw_text like '📊 گزارش ماهانه%%AquaGold%%'
                   or raw_text like '✅ کار در AquaGold ثبت شد%%'
                   or raw_text like '✅ کار انجام شد و در AquaGold ثبت شد%%'
                   or raw_text like '✅ کار از طریق ثبت هوشمند AquaGold%%'
                 )
               returning id"""
        )
        removed = [str(row["id"]) for row in cur.fetchall()]
    if removed:
        app_v3.logger.info("bale_self_generated_jobs_cleaned count=%s", len(removed))
    return removed


# bale_reports already wraps the canonical Bale webhook. Wrap the current view
# function so /reports still works while bot/system messages are stopped first.
_original_webhook = app_v3.app.view_functions.get("bale_webhook")


def _webhook_guard(secret):
    update = request.get_json(silent=True) or {}
    message, text, _chat, sender, _sender_name = bale_bridge._message_payload(update)
    if message and text and is_aquagold_outbound(text, sender):
        return jsonify({"ok": True, "ignored": "aquagold_outbound"})
    return _original_webhook(secret)


if _original_webhook is not None:
    app_v3.app.view_functions["bale_webhook"] = _webhook_guard


# Clean previously-looped report cards whenever the work inbox is opened.
_original_jobs_list = app_v3.app.view_functions.get("bale_jobs_list")


def _jobs_list_with_cleanup():
    _cleanup_self_generated_jobs()
    return _original_jobs_list()


if _original_jobs_list is not None:
    app_v3.app.view_functions["bale_jobs_list"] = _jobs_list_with_cleanup


@app_v3.app.delete("/api/bale/jobs/<job_id>")
@app_v3.roles_required("technician")
def bale_job_discard(job_id):
    """Permanently discard an inbox job that has not entered core services."""
    with app_v3.get_db() as db, db.cursor() as cur:
        cur.execute("select * from bale_jobs where id=%s::uuid for update", (job_id,))
        job = cur.fetchone()
        if not job:
            return jsonify({"ok": True, "already_deleted": True})
        if job.get("status") == "completed" or job.get("service_visit_id"):
            return jsonify({"error": "کار انجام‌شده از اینجا قابل حذف نیست؛ سابقه سرویس/مالی دارد"}), 409
        before = {
            "status": job.get("status"),
            "customer_name": job.get("customer_name"),
            "chat_id": str(job.get("chat_id") or ""),
            "message_id": str(job.get("message_id") or ""),
        }
        app_v3.audit(cur, "bale_job", job_id, "discard", before=before, after={"deleted": True})
        cur.execute("delete from bale_jobs where id=%s::uuid", (job_id,))
    return jsonify({"ok": True, "deleted": True, "job_id": str(job_id)})


BALE_DISCARD_UI_JS = r"""
(()=>{
 const previous=window.app;if(typeof previous!=='function')return;
 window.app=function(){
  const s=previous();
  s.deleteBaleJob=async function(job){
   if(!job||job.status==='completed'||this.baleBusy)return;
   const name=String(job.customer_name||'این کار');
   if(!window.confirm(`«${name}» کاملاً از کارهای بله حذف شود؟\nاین گزینه برای کاری است که نمی‌خواهی وارد اطلاعات AquaGold شود.`))return;
   const id=String(job.id||'');if(!id)return;
   this.baleBusy=true;
   try{
    await this.api('/bale/jobs/'+id,{method:'DELETE'});
    this.baleJobs=(this.baleJobs||[]).filter(item=>String(item.id)!==id);
    await this.loadBaleCounts?.();
    this.toast?.('کار از صندوق بله حذف شد و وارد اطلاعات اصلی نمی‌شود','success');
   }catch(error){this.toast?.(error?.message||'حذف کار انجام نشد','error')}
   finally{this.baleBusy=false}
  };
  return s
 };

 const style=document.createElement('style');
 style.textContent='.bale-hard-delete{width:34px;height:34px;min-width:34px;border-radius:12px;border:1px solid rgba(239,68,68,.28);background:rgba(239,68,68,.10);color:#ef4444;font-size:20px;font-weight:950;line-height:1;display:grid;place-items:center;cursor:pointer;transition:.15s}.bale-hard-delete:active{transform:scale(.92)}';
 document.head.appendChild(style);

 const scan=()=>{
  document.querySelectorAll('.bale-job:not([data-discard-ready])').forEach(article=>{
   article.dataset.discardReady='1';
   let scope=null;try{scope=window.Alpine?.$data?.(article)}catch{}
   const job=scope?.j;
   if(!job||job.status==='completed')return;
   const head=article.querySelector('.bale-job-head');if(!head)return;
   const button=document.createElement('button');button.type='button';button.className='bale-hard-delete';button.title='حذف کامل از کارهای بله';button.setAttribute('aria-label','حذف کامل از کارهای بله');button.textContent='×';
   button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();let live=null;try{live=window.Alpine?.$data?.(article)}catch{};const current=live?.j||job;const fn=live?.deleteBaleJob||scope?.deleteBaleJob;if(typeof fn==='function')fn.call(live||scope,current)});
   head.appendChild(button)
  })
 };
 const start=()=>{scan();const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true})};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
"""


@app_v3.app.get("/bale-discard-ui.js")
def bale_discard_ui_js():
    return Response(BALE_DISCARD_UI_JS, mimetype="application/javascript", headers={"Cache-Control": "no-store, max-age=0"})


@app_v3.app.after_request
def inject_bale_discard_ui(response):
    try:
        if request.path in {"/", "/index.html"} and response.mimetype == "text/html":
            response.direct_passthrough = False
            body = response.get_data(as_text=True)
            if "/bale-discard-ui.js" not in body:
                position = body.lower().find("</head>")
                if position >= 0:
                    tag = '<script src="/bale-discard-ui.js?v=20260831-1"></script>'
                    body = body[:position] + tag + body[position:]
                    response.set_data(body)
                    response.headers["Content-Length"] = str(len(response.get_data()))
            response.headers["Cache-Control"] = "no-store, max-age=0"
    except Exception as exc:
        app_v3.logger.warning("bale_discard_ui_inject_failed detail=%s", str(exc)[:200])
    return response
