/* AquaGold Bale work inbox UI. Loaded before the stable auth finalizer. */
(()=>{
 const base=window.app;if(typeof base!=='function')return;
 window.app=function(){
  const s=base();
  Object.assign(s,{
   baleJobs:[],baleTab:'new',baleCounts:{new:0,review:0,completed:0,cancelled:0},baleMounted:false,baleLoaded:false,
   baleSettings:{enabled:false,auto_reply:true,allowed_chat_ids:[],bot_token_configured:false,bot_token_mask:''},baleToken:'',baleAllowedChats:'',
   baleCompleteJob:null,baleCompleteAmount:'',baleSmartJob:null,baleCancelJob:null,baleCancelReason:'',baleBusy:false
  });
  if(!s.navs.some(n=>n.id==='bale-jobs'))s.navs.splice(Math.min(3,s.navs.length),0,{id:'bale-jobs',label:'کارهای جدید',icon:'services'});
  s.loadBaleCounts=async function(){try{this.baleCounts=await this.api('/bale/jobs/counts')}catch(e){console.warn('Bale counts',e)}};
  s.loadBaleJobs=async function(tab=null){if(tab)this.baleTab=tab;try{this.baleJobs=await this.api('/bale/jobs?status='+encodeURIComponent(this.baleTab))}catch(e){this.toast?.(e.message||'دریافت کارهای بله ناموفق بود','error')}};
  s.loadBaleSettings=async function(){if(!this.canAdmin)return;try{let d=await this.api('/bale/settings');this.baleSettings={...this.baleSettings,...d};this.baleAllowedChats=(d.allowed_chat_ids||[]).join(', ')}catch(e){console.warn('Bale settings',e)}};
  s.saveBaleSettings=async function(){if(!this.canAdmin||this.baleBusy)return;this.baleBusy=true;try{let p={enabled:!!this.baleSettings.enabled,auto_reply:!!this.baleSettings.auto_reply,allowed_chat_ids:this.baleAllowedChats};if(this.baleToken.trim())p.bot_token=this.baleToken.trim();let d=await this.api('/bale/settings',{method:'PATCH',body:JSON.stringify(p)});this.baleSettings={...this.baleSettings,...d};this.baleToken='';this.baleAllowedChats=(d.allowed_chat_ids||[]).join(', ');this.toast?.('اتصال بله ذخیره و Webhook تنظیم شد','success')}catch(e){this.toast?.(e.message||'ذخیره اتصال بله ناموفق بود','error')}finally{this.baleBusy=false}};
  s.testBale=async function(){if(this.baleBusy)return;this.baleBusy=true;try{let d=await this.api('/bale/test',{method:'POST',body:'{}'}),name=d.bot?.username||d.bot?.first_name||d.bot?.id||'ربات';this.toast?.('اتصال بله برقرار است: '+name,'success')}catch(e){this.toast?.(e.message||'اتصال بله برقرار نشد','error')}finally{this.baleBusy=false}};
  s.sendBaleToSmart=async function(job){this.baleSmartJob=job;this.smartText=String(job?.raw_text||'').trim();this.smartParsed=null;this.smartGps={};this.smartSuggestions=[];this.smartCustomerId=job?.customer_id||'';await this.go('smart');setTimeout(()=>this.analyzeSmart?.(),80);this.toast?.('متن کار بله وارد ثبت هوشمند شد؛ GPS و اطلاعات را بررسی و ثبت نهایی کن','success')};
  s.closeBaleComplete=function(){this.baleCompleteJob=null;this.baleCompleteAmount=''};
  s.confirmBaleComplete=async function(){if(!this.baleCompleteJob||this.baleBusy)return;let amount=String(this.baleCompleteAmount||'').replace(/[٬,،\s]/g,'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d));if(!/^\d+$/.test(amount))return this.toast?.('مبلغ دریافتی را وارد کن','error');this.baleBusy=true;try{await this.api('/bale/jobs/'+this.baleCompleteJob.id+'/complete',{method:'POST',body:JSON.stringify({received_amount:Number(amount)})});this.closeBaleComplete();await Promise.all([this.loadBaleJobs(),this.loadBaleCounts()]);this.refreshAll?.().catch(()=>{});this.toast?.('کار انجام‌شده و مبلغ ثبت شد','success')}catch(e){this.toast?.(e.message||'ثبت انجام کار ناموفق بود','error')}finally{this.baleBusy=false}};
  s.openBaleCancel=function(job){this.baleCancelJob=job;this.baleCancelReason='';setTimeout(()=>document.getElementById('baleCancelInput')?.focus(),80)};
  s.closeBaleCancel=function(){this.baleCancelJob=null;this.baleCancelReason=''};
  s.confirmBaleCancel=async function(){if(!this.baleCancelJob||this.baleBusy)return;let reason=String(this.baleCancelReason||'').trim();if(!reason)return this.toast?.('علت کنسل شدن را بنویس','error');this.baleBusy=true;try{await this.api('/bale/jobs/'+this.baleCancelJob.id+'/cancel',{method:'POST',body:JSON.stringify({reason})});this.closeBaleCancel();await Promise.all([this.loadBaleJobs(),this.loadBaleCounts()]);this.toast?.('کار به کارهای کنسل‌شده منتقل شد','success')}catch(e){this.toast?.(e.message||'کنسل کردن کار ناموفق بود','error')}finally{this.baleBusy=false}};
  s.baleStatusLabel=function(j){return j.status==='completed'?'انجام شده':j.status==='cancelled'?'کنسل شده':j.status==='review'?'نیاز به بررسی':'جدید'};
  s.baleMount=function(){
   if(this.baleMounted||!this.token)return;let main=document.querySelector('main.content');if(!main)return;
   this.baleMounted=true;
   let section=document.createElement('section');section.setAttribute('x-show',"page==='bale-jobs'");section.className='bale-page';section.innerHTML=`
   <div class="bale-hero"><div><small>BALE → AQUAGOLD</small><h2>کارهای بله</h2><p>پیام‌های کاری گروه به‌صورت خودکار اینجا جمع می‌شوند.</p></div><div class="bale-orb">💧</div></div>
   <div class="bale-counts"><button class="card bale-count" @click="loadBaleJobs('new')"><small>کارهای جدید</small><strong x-text="Number(baleCounts.new||0).toLocaleString('fa-IR')"></strong></button><button class="card bale-count" @click="loadBaleJobs('completed')"><small>انجام‌شده</small><strong class="text-emerald-500" x-text="Number(baleCounts.completed||0).toLocaleString('fa-IR')"></strong></button><button class="card bale-count" @click="loadBaleJobs('cancelled')"><small>کنسل‌شده</small><strong class="text-red-500" x-text="Number(baleCounts.cancelled||0).toLocaleString('fa-IR')"></strong></button></div>
   <div class="bale-tabs"><button class="btn" :class="baleTab==='new'?'primary':'soft'" @click="loadBaleJobs('new')">جدید</button><button class="btn" :class="baleTab==='completed'?'primary':'soft'" @click="loadBaleJobs('completed')">انجام‌شده</button><button class="btn" :class="baleTab==='cancelled'?'primary':'soft'" @click="loadBaleJobs('cancelled')">کنسل‌شده</button><button class="btn glass" @click="loadBaleJobs();loadBaleCounts()">تازه‌سازی</button></div>
   <div class="bale-job-grid"><template x-for="j in baleJobs" :key="j.id"><article class="card bale-job"><div class="bale-job-head"><div><div class="bale-job-name" x-text="j.customer_name||'کار جدید بله'"></div><div class="bale-job-meta" x-text="[j.chat_title,j.sender_name,persianDateTime(j.received_at)].filter(Boolean).join(' • ')"></div></div><span class="chip" :class="j.status==='completed'?'bg-emerald-500/10 text-emerald-500':j.status==='cancelled'?'bg-red-500/10 text-red-500':'bg-cyan-500/10 text-cyan-500'" x-text="baleStatusLabel(j)"></span></div><div class="flex flex-wrap gap-2 text-sm"><span x-show="j.job_type" class="chip bg-blue-500/10 text-blue-500" x-text="j.job_type"></span><a x-show="j.phone" :href="'tel:'+j.phone" class="chip glass bale-phone" x-text="j.phone"></a></div><div x-show="j.address" class="text-sm muted" x-text="j.address"></div><div class="bale-job-text" x-text="j.raw_text"></div><div x-show="j.status==='completed'" class="rounded-2xl p-3 bg-emerald-500/10"><small class="muted">مبلغ دریافتی</small><b class="block text-emerald-500" x-text="money(j.received_amount||0)+' تومان'"></b></div><div x-show="j.status==='cancelled'" class="rounded-2xl p-3 bg-red-500/10"><small class="muted">علت کنسل شدن</small><b class="block text-red-500" x-text="j.cancel_reason||'—'"></b></div><div x-show="j.status==='new'||j.status==='review'" class="bale-job-actions"><button class="btn primary" @click="sendBaleToSmart(j)">✓ انجام شد → ثبت هوشمند</button><button class="btn bale-cancel" @click="openBaleCancel(j)">× کنسل شد</button></div></article></template></div>
   <div x-show="!baleJobs.length" class="card empty"><div class="empty-icon">📥</div><b x-text="baleTab==='new'?'کار جدیدی از بله نداریم':baleTab==='completed'?'هنوز کاری انجام‌شده ثبت نشده':'هنوز کار کنسل‌شده‌ای نداریم'"></b></div>
   <div x-cloak x-show="baleCompleteJob" style="display:none" class="bale-modal-backdrop" @click.self="closeBaleComplete"><div class="card bale-modal"><h3>ثبت مبلغ دریافتی</h3><p class="text-sm muted mt-1" x-text="baleCompleteJob?.customer_name||'کار بله'"></p><input id="baleAmountInput" x-model="baleCompleteAmount" inputmode="numeric" class="field mt-4" placeholder="مبلغ دریافتی به تومان"><div class="bale-modal-actions"><button class="btn primary" @click="confirmBaleComplete" :disabled="baleBusy">ثبت و انجام شد</button><button class="btn soft" @click="closeBaleComplete">برگشت</button></div></div></div>
   <div x-cloak x-show="baleCancelJob" style="display:none" class="bale-modal-backdrop" @click.self="closeBaleCancel"><div class="card bale-modal"><h3>علت کنسل شدن</h3><p class="text-sm muted mt-1">علت برای سوابق این کار ذخیره می‌شود.</p><textarea id="baleCancelInput" x-model="baleCancelReason" class="field mt-4 min-h-28" placeholder="مثلاً مشتری حضور نداشت، منصرف شد، آدرس اشتباه بود…"></textarea><div class="bale-modal-actions"><button class="btn bale-cancel" @click="confirmBaleCancel" :disabled="baleBusy">ثبت کنسل شدن</button><button class="btn soft" @click="closeBaleCancel">برگشت</button></div></div></div>`;
   main.appendChild(section);if(window.Alpine)Alpine.initTree(section);
   let settings=[...document.querySelectorAll('section')].find(x=>(x.getAttribute('x-show')||'').includes("page==='settings'"));
   if(settings&&!settings.querySelector('.bale-settings')){let card=document.createElement('div');card.setAttribute('x-show','canAdmin');card.className='card p-5 bale-settings';card.innerHTML=`<div class="flex justify-between gap-3"><div><h3 class="section-title">اتصال پیام‌رسان بله</h3><p class="text-sm muted">پیام‌های کاری گروه را مستقیم وارد «کارهای جدید» کن.</p></div><span class="flex items-center gap-2 text-xs"><i class="bale-state-dot" :class="baleSettings.enabled&&baleSettings.webhook_configured?'on':''"></i><span x-text="baleSettings.enabled?'فعال':'غیرفعال'"></span></span></div><div class="grid gap-3 mt-4"><label class="text-sm">توکن ربات <small class="muted" x-text="baleSettings.bot_token_mask||'تنظیم نشده'"></small><input x-model="baleToken" type="password" class="field mt-1" placeholder="توکن جدید را اینجا وارد کن"></label><label class="text-sm">شناسه گروه‌های مجاز <small class="muted">خالی = تمام گروه‌هایی که ربات در آنهاست</small><input x-model="baleAllowedChats" class="field mt-1" placeholder="مثلاً -100123... , -100456..."></label><label class="flex items-center gap-2"><input type="checkbox" x-model="baleSettings.enabled"> اتصال بله فعال باشد</label><label class="flex items-center gap-2"><input type="checkbox" x-model="baleSettings.auto_reply"> بعد از ثبت، ربات در گروه تأیید بفرستد</label></div><div class="grid grid-cols-2 gap-2 mt-4"><button class="btn primary" @click="saveBaleSettings" :disabled="baleBusy">ذخیره و تنظیم Webhook</button><button class="btn soft" @click="testBale" :disabled="baleBusy">تست اتصال ربات</button></div><div class="text-xs muted mt-3">قانون ورود: نام/فامیل + شماره تماس، یا وجود واژه‌های فیلتر، دستگاه، ساید یا یخچال.</div>`;settings.insertBefore(card,settings.firstChild);if(window.Alpine)Alpine.initTree(card)}
  };
  const oldMount=s.mountEnhancements?.bind(s);
  s.mountEnhancements=function(){try{oldMount?.()}catch(e){console.error('AquaGold enhancement mount isolated',e)};try{this.baleMount?.()}catch(e){console.error('Bale mount isolated',e)};try{this.mountAquaAI?.()}catch(e){console.error('Aqua AI mount isolated',e)};if(this.token&&!this.baleLoaded){this.baleLoaded=true;this.loadBaleCounts();this.loadBaleJobs('new');this.loadBaleSettings();this.loadAquaSettings?.()}};
  const oldSmartRegister=s.registerSmart?.bind(s);
  s.registerSmart=async function(){
   const pending=this.baleSmartJob;
   await oldSmartRegister?.();
   if(pending && !this.smartText && !this.smartParsed){
    try{await this.api('/bale/jobs/'+pending.id+'/finalize',{method:'POST',body:'{}'});this.baleSmartJob=null;await Promise.all([this.loadBaleCounts?.(),this.loadBaleJobs?.('new')]);this.toast?.('کار بله از طریق ثبت هوشمند وارد سرویس‌های اصلی شد','success')}catch(e){this.toast?.(e.message||'سرویس ثبت شد ولی اتصال کار بله کامل نشد','error')}
   }
  };
  const oldGo=s.go?.bind(s);
  s.go=async function(page){if(page==='bale-jobs'){this.page=page;await Promise.all([this.loadBaleJobs(this.baleTab||'new'),this.loadBaleCounts()]);return}return oldGo?oldGo(page):void(this.page=page)};
  return s;
 };
})();
